BEGIN;
DROP TABLE IF EXISTS postpost CASCADE;

CREATE TABLE postpost (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  myname VARCHAR(255) NOT NULL,
  post TEXT NOT NULL
);

COMMIT;
